structure Tokens : Tiger_TOKENS =
struct
  (* A "scaffold" structure for debugging lexers. *)

 fun linePosString(line, col) =
 	":" ^ Int.toString(line) ^ "." ^ Int.toString(col)

type linenum = int
type token = string
fun TYPE(i,j) = "TYPE   " ^ linePosString(i, j)
fun VAR(i,j) = "VAR   " ^ linePosString(i, j)
fun FUNCTION(i,j) = "FUNCTION   " ^ linePosString(i, j)
fun BREAK(i,j) = "BREAK   " ^ linePosString(i, j)
fun OF(i,j) = "OF   " ^ linePosString(i, j)
fun END(i,j) = "END   " ^ linePosString(i, j)
fun IN(i,j) = "IN   " ^ linePosString(i, j)
fun NIL(i,j) = "NIL   " ^ linePosString(i, j)
fun LET(i,j) = "LET   " ^ linePosString(i, j)
fun DO(i,j) = "DO   " ^ linePosString(i, j)
fun TO(i,j) = "TO   " ^ linePosString(i, j)
fun FOR(i,j) = "FOR   " ^ linePosString(i, j)
fun WHILE(i,j) = "WHILE   " ^ linePosString(i, j)
fun ELSE(i,j) = "ELSE   " ^ linePosString(i, j)
fun THEN(i,j) = "THEN   " ^ linePosString(i, j)
fun IF(i,j) = "IF   " ^ linePosString(i, j)
fun ARRAY(i,j) = "ARRAY   " ^ linePosString(i, j)
fun ASSIGN(i,j) = "ASSIGN   " ^ linePosString(i, j)
fun OR(i,j) = "OR   " ^ linePosString(i, j)
fun AND(i,j) = "AND   " ^ linePosString(i, j)
fun GE(i,j) = "GE   " ^ linePosString(i, j)
fun GT(i,j) = "GT   " ^ linePosString(i, j)
fun LE(i,j) = "LE   " ^ linePosString(i, j)
fun LT(i,j) = "LT   " ^ linePosString(i, j)
fun NEQ(i,j) = "NEQ   " ^ linePosString(i, j)
fun EQ(i,j) = "EQ   " ^ linePosString(i, j)
fun DIVIDE(i,j) = "DIVIDE   " ^ linePosString(i, j)
fun TIMES(i,j) = "TIMES   " ^ linePosString(i, j)
fun MINUS(i,j) = "MINUS   " ^ linePosString(i, j)
fun PLUS(i,j) = "PLUS   " ^ linePosString(i, j)
fun DOT(i,j) = "DOT   " ^ linePosString(i, j)
fun RBRACE(i,j) = "RBRACE   " ^ linePosString(i, j)
fun LBRACE(i,j) = "LBRACE   " ^ linePosString(i, j)
fun RBRACK(i,j) = "RBRACK   " ^ linePosString(i, j)
fun LBRACK(i,j) = "LBRACK   " ^ linePosString(i, j)
fun RPAREN(i,j) = "RPAREN   " ^ linePosString(i, j)
fun LPAREN(i,j) = "LPAREN   " ^ linePosString(i, j)
fun SEMICOLON(i,j) = "SEMICOLON   " ^ linePosString(i, j)
fun COLON(i,j) = "COLON   " ^ linePosString(i, j)
fun COMMA(i,j) = "COMMA   " ^ linePosString(i, j)
fun STRING(s,i,j) = "STRING("^s^")     " ^ linePosString(i, j)
fun INT(c,i,j) = "INT("^Int.toString(c)^")   " ^ linePosString(i, j)
fun ID(s,i,j) = "ID("^s^")     " ^ linePosString(i, j)
fun EOF(i,j) = "EOF   " ^ linePosString(i, j)
end
